# Generated by Django 4.1.4 on 2022-12-21 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Person",),
    ]
